cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  datasource:
    url: jdbc:mysql://${URL}:3306/3dbox?serverTimezone=Asia/Seoul
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
oauth:
  kakao:
    client_id: ${CLIENT_ID} # REST API ?
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: ${CLIENT_SECRET} # Client Secret ?
    scope: profile_nickname, profile_image